const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "Fake imdb api",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:1312",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Film",
            "description": "Endpoints"
        },
        {
            "name": "Serie",
            "description": "Endpoints"
        }
    ],
    definitions: {
        Film: {
            titre: "Ice Age: Dawn of the dinosaurs",
            synopsis: "Ellie is pregnant, making Manny excited and overprotective. However, this causes him to become distant and negligent of Diego, who debates whether he should leave the herd because he thinks that he's losing his edge as a hunter and isn't meant for the family life, and Sid, who begins to wish for a family of his own and adopts three apparently lost eggs that he finds in a cave. Manny tells Sid to put the eggs back, but Sid ignores him and looks after them, which hatch into baby Tyrannosaurus rex the next morning. ",
            annee: "2009",
            duree: "94",
            posterImage: "https://lumiere-a.akamaihd.net/v1/images/p_iceagedawnofthedinosaurs_21384_b145ad3f.jpeg"
        },
        Serie: {
            titre: "The Magicians",
            synopsis: "Quentin Coldwater enrolls at Brakebills University for Magical Pedagogy to be trained as a magician, where he discovers that the magical world from his favorite childhood book is real and poses a danger to humanity. Meanwhile, the life of his childhood friend Julia is derailed when she is denied entry, and she searches for magic elsewhere outside of the school. ",
            annee: "2015-2020",
            duree: "41-52",
            posterImage: "https://images.justwatch.com/poster/38148297/s718/the-magicians.%7Bformat%7D",
            productionStatus: "Ended",
            nombreSaisons: "5"
        }
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./api.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./api.js')
})